import type { RefObject } from 'react'
import type { RecorderContextValue } from '../context/RecorderContext'

export function createRecorderContextValue(overrides: Partial<RecorderContextValue> = {}): RecorderContextValue {
  const value = {
    activeSession: {
      id: 'session-1',
      title: 'Session 01',
      status: 'stopped',
      createdAt: 1_700_000_000_000,
      updatedAt: 1_700_000_000_000,
      durationMs: 12_000,
      size: 4_096,
      mimeType: 'audio/webm',
      chunkCount: 2,
    },
    canRecord: true,
    clearOfflineQueue: async () => undefined,
    closeRecorder: () => undefined,
    createSession: async () => undefined,
    elapsedMs: 12_000,
    error: null,
    exportMp3: async () => undefined,
    exportProgress: 0,
    isExporting: false,
    isFinalized: true,
    isPreviewPlaying: false,
    isTranscribing: false,
    micProcessing: {
      echoCancellation: true,
      noiseSuppression: true,
      autoGainControl: true,
    },
    mimeType: 'audio/webm',
    mp3ExportSettings: { bitRate: 32, channelCount: 1 },
    openSession: () => undefined,
    pauseRecording: () => undefined,
    queueStats: { chunks: 2, bytes: 4_096, sessions: 1 },
    recordedBlob: new Blob(['audio'], { type: 'audio/webm' }),
    recordedUrl: 'blob:test',
    remainingMs: 14_388_000,
    removeSession: async () => undefined,
    resumeRecording: () => undefined,
    sessionCacheBytes: 4_096,
    sessionChunks: [
      { id: 'chunk-1', sessionId: 'session-1', sequence: 0, createdAt: 1, size: 2_048, type: 'audio/webm' },
      { id: 'chunk-2', sessionId: 'session-1', sequence: 1, createdAt: 2, size: 2_048, type: 'audio/webm' },
    ],
    sessions: [],
    setMp3BitRate: () => undefined,
    setMp3ChannelCount: () => undefined,
    startRecording: async () => undefined,
    status: 'stopped',
    statusLabel: 'stopped',
    stopRecording: () => undefined,
    toggleMicProcessing: () => undefined,
    togglePreview: async () => undefined,
    transcript: {
      id: 't1',
      text: 'Testing transcript',
      confidence: 0.8,
      createdAt: 3,
      segments: [{ id: 'segment-1', text: 'Testing transcript', confidence: 0.8, startMs: 1_000, endMs: 2_400 }],
    },
    view: 'recorder',
    waveformMountKey: 0,
    waveformRef: { current: null } as RefObject<HTMLDivElement | null>,
    ...overrides,
  }

  return value as RecorderContextValue
}
