declare const styles: {
  readonly activeSegment: string
  readonly appShell: string
  readonly button: string
  readonly channelSetting: string
  readonly chunkList: string
  readonly chunkRow: string
  readonly controlDeck: string
  readonly emptyLibrary: string
  readonly emptyStrip: string
  readonly errorBanner: string
  readonly eyebrow: string
  readonly exportSettings: string
  readonly finalizedStrip: string
  readonly iconButton: string
  readonly libraryHero: string
  readonly librarySummary: string
  readonly meterGrid: string
  readonly micOptions: string
  readonly newSessionButton: string
  readonly panelHeading: string
  readonly previewStrip: string
  readonly primaryButton: string
  readonly progressTrack: string
  readonly recorderStage: string
  readonly sectionTitle: string
  readonly segmentButton: string
  readonly segmentedControl: string
  readonly sessionCard: string
  readonly sessionLibrary: string
  readonly sessionList: string
  readonly sessionOpen: string
  readonly sessionStatus: string
  readonly selectField: string
  readonly selectInput: string
  readonly splitActions: string
  readonly statusPill: string
  readonly subtle: string
  readonly title: string
  readonly toggleOption: string
  readonly toolPanel: string
  readonly topbar: string
  readonly topbarActions: string
  readonly transcriptBox: string
  readonly transcriptPanel: string
  readonly waveHeader: string
  readonly wavePanel: string
  readonly waveRecordButton: string
  readonly waveformFrame: string
  readonly waveform: string
  readonly wideButton: string
  readonly workspace: string
}

export default styles
