declare const styles: {
  readonly "audioPreview": string;
  readonly "body": string;
  readonly "button": string;
  readonly "buttonDanger": string;
  readonly "buttonRow": string;
  readonly "buttonSecondary": string;
  readonly "empty": string;
  readonly "errorBox": string;
  readonly "field": string;
  readonly "header": string;
  readonly "heapSpark": string;
  readonly "input": string;
  readonly "metric": string;
  readonly "node": string;
  readonly "partial": string;
  readonly "pulse": string;
  readonly "queueArrowIn": string;
  readonly "queueArrowOut": string;
  readonly "queueHead": string;
  readonly "queueLog": string;
  readonly "queueRow": string;
  readonly "recordDot": string;
  readonly "select": string;
  readonly "statusDot": string;
  readonly "statusErr": string;
  readonly "statusIdle": string;
  readonly "statusOk": string;
  readonly "statusRow": string;
  readonly "statusWarn": string;
  readonly "timeline": string;
  readonly "timelineFill": string;
  readonly "timelineLabel": string;
  readonly "toggleRow": string;
  readonly "transcriptList": string;
};
export = styles;

